version: '3.8'

services:
  # AquilaCMS Service
  aquilacms:
    image: aquilacms/aquilacms
    ports:
      - "3010:3010"
    environment:
      - MONGO_URI=mongodb://rohan:rohanpass@<host_name or host_ip>:27017/aquilacms
    depends_on:
      - mongo
    networks:
      - aquilacms_network

  # MongoDB Service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rohan
      - MONGO_INITDB_ROOT_PASSWORD=rohanpass
    networks:
      - aquilacms_network

networks:
  aquilacms_network:
    driver: bridge

volumes:
  mongo_data: